# utils.py

SKILL_NORMALIZATION_MAP = {
    # Programming Languages & Scripting
    "python programming": "python", "pyhton": "python", "py": "python", # Common typo and abbreviation
    "java programming": "java", "core java": "java",
    "javascripting": "javascript", "javasript": "javascript", "js": "javascript", "es6": "javascript", "ecmascript": "javascript",
    "c#": "c-sharp", "c sharp": "c-sharp", "csharp": "c-sharp",
    "c++": "c-plus-plus", "cpp": "c-plus-plus", "c plus plus": "c-plus-plus",
    "php scripting": "php",
    "ruby on rails": "ruby", "ror": "ruby", "ruby": "ruby",
    "golang": "go", "go lang": "go",
    "swift programming": "swift",
    "kotlin programming": "kotlin",
    "scala programming": "scala",
    "r programming": "r", "rstats": "r",
    "typescript": "typescript", "ts": "typescript",
    "visual basic": "vb.net", "vb": "vb.net", "visualbasic": "vb.net",
    "shell scripting": "shell script", "bash scripting": "shell script", "bash": "shell script", "shell": "shell script",
    "powershell": "powershell",

    # Web Frameworks & Libraries
    "reactjs": "react", "react.js": "react", "react": "react",
    "angularjs": "angular", "angular.js": "angular", "angular 2+": "angular", "angular": "angular",
    "vue.js": "vue", "vuejs": "vue", "vue": "vue",
    "node.js": "node", "nodejs": "node", "node": "node",
    "express.js": "express", "expressjs": "express", "express": "express",
    "django framework": "django", "django": "django",
    "flask framework": "flask", "flask": "flask",
    "spring framework": "spring", "spring boot": "spring", "spring": "spring",
    ".net core": "dotnet-core", ".net": "asp-dotnet", "dotnet": "asp-dotnet",
    "jquery": "jquery",
    "bootstrap framework": "bootstrap", "bootstrap": "bootstrap",

    # Databases & Data Storage
    "sql server": "sql", "ms sql": "sql", "mssql": "sql", "t-sql": "sql",
    "mysql": "sql",
    "postgresql": "sql", "postgres": "sql", "postgressql": "sql",
    "oracle db": "oracle", "oracle database": "oracle", "oracle": "oracle",
    "sqlite": "sqlite",
    "mongodb": "mongodb", "mongo": "mongodb", "mongoose": "mongodb",
    "cassandra": "cassandra",
    "redis": "redis",
    "elasticsearch": "elasticsearch", "elastic search": "elasticsearch", "elastic": "elasticsearch",
    "dynamodb": "dynamodb",
    "firebase": "firebase",
    "data warehousing": "data warehouse",
    "etl processes": "etl", "extract transform load": "etl",

    # Cloud Platforms & Services
    "aws": "amazon web services", "amazon web services (aws)": "amazon web services", "amazonwebservices": "amazon web services",
    "amazon s3": "amazon s3", "s3": "amazon s3",
    "amazon ec2": "amazon ec2", "ec2": "amazon ec2",
    "aws lambda": "aws lambda", "lambda": "aws lambda",
    "gcp": "google cloud platform", "google cloud": "google cloud platform", "googlecloud": "google cloud platform",
    "google compute engine": "google compute engine",
    "google cloud functions": "google cloud functions",
    "azure": "microsoft azure", "ms azure": "microsoft azure", "azure cloud": "microsoft azure",
    "azure functions": "azure functions",
    "azure blob storage": "azure blob storage",
    "kubernetes": "kubernetes", "k8s": "kubernetes", "kube": "kubernetes",
    "docker": "docker", "docker containers": "docker",
    "serverless architecture": "serverless", "serverless": "serverless",
    "iaas": "iaas", "paas": "paas", "saas": "saas",

    # ML/AI & Data Science
    "machine learning (ml)": "machine learning", "ml": "machine learning", "machinelearning": "machine learning",
    "deep learning (dl)": "deep learning", "dl": "deep learning", "neural networks": "neural networks", "deeplearning": "deep learning",
    "artificial intelligence (ai)": "artificial intelligence", "ai": "artificial intelligence", "artificialintelligence": "artificial intelligence",
    "natural language processing": "nlp", "nlp techniques": "nlp", "natural language": "nlp",
    "computer vision": "computer vision", "cv": "computer vision", "computervision": "computer vision",
    "data analysis": "data analysis", "data analytics": "data analysis", "dataanalyst": "data analysis",
    "data visualization": "data visualization", "dataviz": "data visualization", "datavisualization": "data visualization",
    "tableau software": "tableau", "tableau": "tableau",
    "power bi": "powerbi", "microsoft power bi": "powerbi", "powerbi": "powerbi",
    "pandas library": "pandas", "pandas": "pandas",
    "numpy library": "numpy", "numpy": "numpy",
    "scikit-learn": "scikit-learn", "sklearn": "scikit-learn", "scikitlearn": "scikit-learn",
    "tensorflow framework": "tensorflow", "keras": "tensorflow", "tensorflow": "tensorflow",
    "pytorch framework": "pytorch", "pytorch": "pytorch",
    "big data technologies": "big data", "hadoop": "hadoop", "spark": "spark", "apache spark": "apache spark", "bigdata": "big data",
    "statistics": "statistical analysis", "statistical modeling": "statistical analysis", "stats": "statistical analysis",

    # DevOps & Tools
    "git version control": "git", "github": "github", "gitlab": "gitlab", "bitbucket": "bitbucket", "git": "git",
    "ci/cd": "cicd", "continuous integration": "cicd", "continuous deployment": "cicd", "cicd pipelines": "cicd",
    "jenkins": "jenkins",
    "ansible": "ansible",
    "terraform": "terraform",
    "jira": "jira", "atlassian jira": "jira", "atlassian": "jira",
    "agile methodologies": "agile", "scrum master": "agile", "scrum": "agile", "kanban": "kanban", "agile development": "agile",

    # Operating Systems
    "linux os": "linux", "unix environment": "unix", "linux": "linux",
    "windows server": "windows server", "windows": "windows server",
    "macos": "macos", "mac os": "macos",

    # Software Engineering & Design
    "software development life cycle": "sdlc", "sdlc": "sdlc",
    "object-oriented programming": "oop", "object oriented design": "oop", "objectorientedprogramming": "oop",
    "rest apis": "restful apis", "restful services": "restful apis", "api design": "api design", "rest": "restful apis",
    "microservices architecture": "microservices", "microservices": "microservices",
    "design patterns": "design patterns", "software design": "design patterns",
    "software testing": "qa testing", "quality assurance": "qa testing", "automated testing": "automated testing", "testing": "qa testing",
    "unit testing": "unit testing", "integration testing": "integration testing", "test driven development": "unit testing",

    # Business & Soft Skills
    "excel": "microsoft excel", "ms excel": "microsoft excel", "excel skills": "microsoft excel",
    "spreadsheets": "spreadsheet software", "spreadsheet": "spreadsheet software",
    "microsoft office suite": "microsoft office", "ms office": "microsoft office", "office suite": "microsoft office",
    "powerpoint": "powerpoint", "ms powerpoint": "powerpoint", "power point": "powerpoint",
    "communication skills": "communication", "verbal communication": "communication", "written communication": "communication", "communications": "communication",
    "team work": "teamwork", "collaboration skills": "teamwork", "team player": "teamwork", "team": "teamwork",
    "problem-solving": "problem solving", "analytical skills": "analytical skills", "analysis": "analytical skills",
    "project management": "project management", "project planning": "project management", "project": "project management",
    "leadership skills": "leadership", "team leadership": "leadership", "leadership": "leadership",
    "time management": "time management", "organization skills": "time management",
    "customer service": "customer support", "client facing skills": "customer support", "customer relations": "customer support",
    "technical support": "technical support", "tech support": "technical support",
    "data entry": "data entry",
    "sales skills": "sales", "business development": "sales", "selling": "sales",
    "marketing skills": "marketing", "digital marketing": "marketing", "seo": "seo", "sem": "sem", "marketing strategy": "marketing",
    "content creation": "content writing", "copywriting": "content writing", "content writing": "content writing",
    "graphic design": "graphic design", "adobe photoshop": "adobe creative suite", "adobe illustrator": "adobe creative suite", "adobe indesign": "adobe creative suite", "adobe creative suite": "adobe creative suite",
    "ux design": "ux design", "ui design": "ui/ux design", "user interface design": "ui/ux design", "user experience": "ux design", "user experience design": "ux design", "ui/ux": "ui/ux design",
    "front end development": "front end development", "front end": "front end development", "frontend": "front end development",
    "back end development": "back end development", "back end": "back end development", "backend": "back end development",
    "full stack development": "full stack development", "fullstack": "full stack development", "full stack": "full stack development",
    "network engineering": "network engineering", "networking": "network engineering",
    "cyber security": "cyber security", "information security": "cyber security", "security": "cyber security",
    "cloud computing": "cloud computing", "cloud solutions": "cloud computing",
    "database administration": "database administration", "dba": "database administration",
    "systems administration": "systems administration", "sysadmin": "systems administration",
    "technical writing": "technical writing", "documentation": "technical writing",
    "business analysis": "business analysis", "business intelligence": "business analysis",
    "financial analysis": "financial analysis", "financial modeling": "financial analysis",
    "human resources": "human resources", "hr": "human resources",
    "project coordination": "project coordination", "project administration": "project coordination",
    "event planning": "event planning",
    "public relations": "public relations", "pr": "public relations",
    "supply chain management": "supply chain management", "scm": "supply chain management",
    "logistics management": "logistics management",
    "data governance": "data governance",
    "risk management": "risk management",
    "compliance": "compliance",
    "auditing": "auditing",
    "legal compliance": "legal compliance",
    "regulatory compliance": "regulatory compliance",
    "quality control": "quality control",
    "process improvement": "process improvement",
    "lean manufacturing": "lean manufacturing",
    "six sigma": "six sigma",
    "business strategy": "business strategy",
    "market research": "market research",
    "competitive analysis": "competitive analysis",
    "mergers and acquisitions": "mergers and acquisitions",
    "investment management": "investment management",
    "portfolio management": "portfolio management",
    "wealth management": "wealth management",
    "financial planning": "financial planning",
    "tax planning": "tax planning",
    "estate planning": "estate planning",
    "retirement planning": "retirement planning",
    "insurance planning": "insurance planning",
    "risk assessment": "risk assessment",
    "fraud detection": "fraud detection",
    "anti-money laundering": "anti-money laundering",
    "know your customer": "know your customer",
    "regulatory reporting": "regulatory reporting",
    "internal controls": "internal controls",
    "corporate governance": "corporate governance",
    "ethics": "ethics",
    "corporate social responsibility": "corporate social responsibility",
    "sustainability": "sustainability",
    "environmental management": "environmental management",
    "social impact": "social impact",
    "governance risk and compliance": "governance risk and compliance",
    "information technology governance": "information technology governance",
    "it governance": "information technology governance",
    "enterprise risk management": "enterprise risk management",
    "operational risk management": "operational risk management",
    "credit risk management": "credit risk management",
    "market risk management": "market risk management",
    "liquidity risk management": "liquidity risk management",
    "insurance": "insurance",
    "reinsurance": "reinsurance",
    "actuarial science": "actuarial science",
    "underwriting": "underwriting",
    "claims management": "claims management",
    "loss adjusting": "loss adjusting",
    "risk engineering": "risk engineering",
    "business continuity planning": "business continuity planning",
    "disaster recovery planning": "disaster recovery planning",
    "crisis management": "crisis management",
    "emergency management": "emergency management",
    "security management": "security management",
    "physical security": "physical security",
    "personnel security": "personnel security",
    "information security management": "information security management",
    "it security management": "information security management",
    "data security": "data security",
    "network security": "network security",
    "application security": "application security",
    "endpoint security": "endpoint security",
    "cloud security": "cloud security",
    "mobile security": "mobile security",
    "internet of things security": "internet of things security",
    "iot security": "internet of things security",
    "industrial control systems security": "industrial control systems security",
    "ics security": "industrial control systems security",
    "supervisory control and data acquisition security": "supervisory control and data acquisition security",
    "scada security": "supervisory control and data acquisition security",
    "operational technology security": "operational technology security",
    "ot security": "operational technology security",
    "critical infrastructure security": "critical infrastructure security",
    "national security": "national security",
    "homeland security": "homeland security",
    "law enforcement": "law enforcement",
    "intelligence analysis": "intelligence analysis",
    "counterterrorism": "counterterrorism",
    "cyber warfare": "cyber warfare",
    "information warfare": "information warfare",
    "psychological warfare": "psychological warfare",
    "electronic warfare": "electronic warfare",
    "military intelligence": "military intelligence",
    "defense intelligence": "defense intelligence",
    "national intelligence": "national intelligence",
    "strategic intelligence": "strategic intelligence",
    "tactical intelligence": "tactical intelligence",
    "operational intelligence": "operational intelligence",
    "human intelligence": "human intelligence",
    "humint": "human intelligence",
    "signals intelligence": "signals intelligence",
    "sigint": "signals intelligence",
    "imagery intelligence": "imagery intelligence",
    "imint": "imagery intelligence",
    "measurement and signature intelligence": "measurement and signature intelligence",
    "masint": "measurement and signature intelligence",
    "open source intelligence": "open source intelligence",
    "osint": "open source intelligence",
    "geospatial intelligence": "geospatial intelligence",
    "geoint": "geospatial intelligence",
    "technical intelligence": "technical intelligence",
    "techint": "technical intelligence",
    "medical intelligence": "medical intelligence",
    "medint": "medical intelligence",
    "economic intelligence": "economic intelligence",
    "econtint": "economic intelligence",
    "financial intelligence": "financial intelligence",
    "fintint": "financial intelligence",
    "maritime intelligence": "maritime intelligence",
    "mintint": "maritime intelligence",
    "space intelligence": "space intelligence",
    "spintint": "space intelligence",
    "nuclear intelligence": "nuclear intelligence",
    "nuintint": "nuclear intelligence",
    "chemical intelligence": "chemint",
    "biological intelligence": "bioint",
    "radiological intelligence": "radint",
    "nuclear biological and chemical intelligence": "nbcint",
    "nbc intelligence": "nbcint",
    "explosive ordnance disposal": "explosive ordnance disposal",
    "eod": "explosive ordnance disposal",
    "counter explosive hazards": "counter explosive hazards",
    "ceh": "counter explosive hazards",
    "improvised explosive device disposal": "improvised explosive device disposal",
    "iedd": "improvised explosive device disposal",
    "counter improvised explosive device": "counter improvised explosive device",
    "cied": "counter improvised explosive device",
    "bomb disposal": "bomb disposal",
    "demining": "demining",
    "mine clearance": "mine clearance",
    "unexploded ordnance disposal": "unexploded ordnance disposal",
    "uxo disposal": "unexploded ordnance disposal",
    "landmine disposal": "landmine disposal",
    "maritime mine disposal": "maritime mine disposal",
    "underwater mine disposal": "underwater mine disposal",
    "naval mine disposal": "naval mine disposal",
    "airborne mine disposal": "airborne mine disposal",
    "space mine disposal": "space mine disposal",
    "nuclear mine disposal": "nuclear mine disposal",
    "chemical mine disposal": "chemical mine disposal",
    "biological mine disposal": "biological mine disposal",
    "radiological mine disposal": "radiological mine disposal",
    "nuclear biological and chemical mine disposal": "nuclear biological and chemical mine disposal",
    "nbc mine disposal": "nuclear biological and chemical mine disposal",
    "explosive ordnance reconnaissance": "explosive ordnance reconnaissance",
    "eor": "explosive ordnance reconnaissance",
    "counter explosive hazards reconnaissance": "counter explosive hazards reconnaissance",
    "cehr": "counter explosive hazards reconnaissance",
    "improvised explosive device reconnaissance": "improvised explosive device reconnaissance",
    "iedr": "improvised explosive device reconnaissance",
    "counter improvised explosive device reconnaissance": "counter improvised explosive device reconnaissance",
    "ciedr": "counter improvised explosive device reconnaissance",
    "bomb reconnaissance": "bomb reconnaissance",
    "mine reconnaissance": "mine reconnaissance",
    "unexploded ordnance reconnaissance": "unexploded ordnance reconnaissance",
    "uxo reconnaissance": "unexploded ordnance reconnaissance",
    "landmine reconnaissance": "landmine reconnaissance",
    "maritime mine reconnaissance": "maritime mine reconnaissance",
    "underwater mine reconnaissance": "underwater mine reconnaissance",
    "naval mine reconnaissance": "naval mine reconnaissance",
    "airborne mine reconnaissance": "airborne mine reconnaissance",
    "space mine reconnaissance": "space mine reconnaissance",
    "nuclear mine reconnaissance": "nuclear mine reconnaissance",
    "chemical mine reconnaissance": "chemical mine reconnaissance",
    "biological mine reconnaissance": "biological mine reconnaissance",
    "radiological mine reconnaissance": "radiological mine reconnaissance",
    "nuclear biological and chemical mine reconnaissance": "nuclear biological and chemical mine reconnaissance",
    "nbc mine reconnaissance": "nuclear biological and chemical mine reconnaissance",
    "explosive ordnance security": "explosive ordnance security",
    "eos": "explosive ordnance security",
    "counter explosive hazards security": "counter explosive hazards security",
    "cehs": "counter explosive hazards security",
    "improvised explosive device security": "improvised explosive device security",
    "ieds": "improvised explosive device security",
    "counter improvised explosive device security": "counter improvised explosive device security",
    "cieds": "counter improvised explosive device security",
    "bomb security": "bomb security",
    "mine security": "mine security",
    "unexploded ordnance security": "unexploded ordnance security",
    "uxo security": "unexploded ordnance security",
    "landmine security": "landmine security",
    "maritime mine security": "maritime mine security",
    "underwater mine security": "underwater mine security",
    "naval mine security": "naval mine security",
    "airborne mine security": "airborne mine security",
    "space mine security": "space mine security",
    "nuclear mine security": "nuclear mine security",
    "chemical mine security": "chemical mine security",
    "biological mine security": "biological mine security",
    "radiological mine security": "radiological mine security",
    "nuclear biological and chemical mine security": "nuclear biological and chemical mine security",
    "nbc mine security": "nuclear biological and chemical mine security",
    "explosive ordnance safety": "explosive ordnance safety",
    "eosa": "explosive ordnance safety",
    "counter explosive hazards safety": "counter explosive hazards safety",
    "cehsa": "counter explosive hazards safety",
    "improvised explosive device safety": "improvised explosive device safety",
    "iedsa": "improvised explosive device safety",
    "counter improvised explosive device safety": "counter improvised explosive device safety",
    "ciedsa": "counter improvised explosive device safety",
    "bomb safety": "bomb safety",
    "mine safety": "mine safety",
    "unexploded ordnance safety": "unexploded ordnance safety",
    "uxo safety": "unexploded ordnance safety",
    "landmine safety": "landmine safety",
    "maritime mine safety": "maritime mine safety",
    "underwater mine safety": "underwater mine safety",
    "naval mine safety": "naval mine safety",
    "airborne mine safety": "airborne mine safety",
    "space mine safety": "space mine safety",
    "nuclear mine safety": "nuclear mine safety",
    "chemical mine safety": "chemical mine safety",
    "biological mine safety": "biological mine safety",
    "radiological mine safety": "radiological mine safety",
    "nuclear biological and chemical mine safety": "nuclear biological and chemical mine safety",
    "nbc mine safety": "nuclear biological and chemical mine safety",
    # Add more as needed
}

def normalize_skill(skill_text, normalization_map):
    """Normalizes a single skill string."""
    if not isinstance(skill_text, str):
        return "" # Or handle as an error/log
    cleaned_skill = skill_text.lower().strip()
    # Expand acronyms before normalization
    cleaned_skill = expand_acronyms(cleaned_skill)
    return normalization_map.get(cleaned_skill, cleaned_skill) # Return mapped value or original cleaned skill

def normalize_skill_list(skills, normalization_map):
    """Normalizes a list of skill strings and returns a list of unique canonical skills."""
    if not skills:
        return []
    
    # Handle cases where 'skills' might be a single string instead of a list (e.g. from bad CSV parsing before splitting)
    if isinstance(skills, str):
        # This assumes skills in a string are comma-separated if not already a list
        # This is a fallback; ideally, the input 'skills' should already be a list of strings.
        skills = [s.strip() for s in skills.split(',') if s.strip()]

    normalized_set = set()
    for skill in skills:
        if isinstance(skill, str): # Ensure each item in the list is a string
            normalized_set.add(normalize_skill(skill, normalization_map))
        # else: log or handle non-string item
    return sorted(list(normalized_set))

def expand_acronyms(text):
    """Expands common acronyms related to skills."""
    acronyms = {
        "ml": "machine learning",
        "ai": "artificial intelligence",
        "dl": "deep learning",
        "nlp": "natural language processing",
        "cv": "computer vision",
        "aws": "amazon web services",
        "gcp": "google cloud platform",
        "azure": "microsoft azure",
        "k8s": "kubernetes",
        "cicd": "continuous integration continuous deployment",
        "oop": "object oriented programming",
        "rest": "representational state transfer",
        "ux": "user experience",
        "ui": "user interface",
        "dba": "database administrator",
        "hr": "human resources",
        "pr": "public relations",
        "scm": "supply chain management",
        "eod": "explosive ordnance disposal",
        "ceh": "counter explosive hazards",
        "iedd": "improvised explosive device disposal",
        "cied": "counter improvised explosive device",
        "uxo": "unexploded ordnance",
        "eor": "explosive ordnance reconnaissance",
        "cehr": "counter explosive hazards reconnaissance",
        "iedr": "improvised explosive device reconnaissance",
        "ciedr": "counter improvised explosive device reconnaissance",
        "eos": "explosive ordnance security",
        "cehs": "counter explosive hazards security",
        "ieds": "improvised explosive device security",
        "cieds": "counter improvised explosive device security",
        "eosa": "explosive ordnance safety",
        "cehsa": "counter explosive hazards safety",
        "iedsa": "improvised explosive device safety",
        "ciedsa": "counter improvised explosive device safety",
        "nbc": "nuclear biological and chemical",
        "humint": "human intelligence",
        "sigint": "signals intelligence",
        "imint": "imagery intelligence",
        "masint": "measurement and signature intelligence",
        "osint": "open source intelligence",
        "geoint": "geospatial intelligence",
        "techint": "technical intelligence",
        "medint": "medical intelligence",
        "econtint": "economic intelligence",
        "fintint": "financial intelligence",
        "mintint": "maritime intelligence",
        "spintint": "space intelligence",
        "nuintint": "nuclear intelligence",
        "chemint": "chemical intelligence",
        "bioint": "biological intelligence",
        "radint": "radiological intelligence",
        "nbcint": "nuclear biological and chemical intelligence",
    }
    words = text.split()
    expanded_words = [acronyms.get(word, word) for word in words]
    return " ".join(expanded_words)